mappings:
  BoltHtmlEditorField_Toolbar: ChristopherBolt\BoltTools\Anchors\BoltHtmlEditorField_Toolbar
  BoltSiteTreeLinkTracking_Parser: ChristopherBolt\BoltTools\Anchors\BoltSiteTreeLinkTracking_Parser
  BoltSiteMap: ChristopherBolt\BoltTools\Controllers\BoltSiteMap
  BoltSiteSearch: ChristopherBolt\BoltTools\Controllers\BoltSiteSearch
  BoltBlogPost_Controller: ChristopherBolt\BoltTools\Extensions\BoltBlogPost_Controller
  BoltBlog_Controller: ChristopherBolt\BoltTools\Extensions\BoltBlog_Controller
  BoltBlog: ChristopherBolt\BoltTools\Extensions\BoltBlog
  BoltBlogCategory: ChristopherBolt\BoltTools\Extensions\BoltBlogCategory
  BoltBlogPost: ChristopherBolt\BoltTools\Extensions\BoltBlogPost
  BoltDBFieldExtension: ChristopherBolt\BoltTools\Extensions\BoltDBFieldExtension
  BoltLink: ChristopherBolt\BoltTools\Extensions\BoltLink
  BoltLinkField: ChristopherBolt\BoltTools\Extensions\BoltLinkField
  BoltMember: ChristopherBolt\BoltTools\Extensions\BoltMember
  BoltSiteTree: ChristopherBolt\BoltTools\Extensions\BoltSiteTree
  BoltSiteTree_Controller: ChristopherBolt\BoltTools\Extensions\BoltSiteTree_Controller
  BoltTextExtension: ChristopherBolt\BoltTools\Extensions\BoltTextExtension
  BoltToolsLeftAndMain: ChristopherBolt\BoltTools\Extensions\BoltToolsLeftAndMain
  DefaultCan: ChristopherBolt\BoltTools\Extensions\DefaultCan
  DefaultSort: Christop~erBolt\BoltTools\Extensions\DefaultSort
  AddNewDropDownField: ChristopherBolt\BoltTools\Forms\AddNewDropDownField
  AddNewListboxField: ChristopherBolt\BoltTools\Forms\AddNewListboxField
  GroupedListboxField: ChristopherBolt\BoltTools\Forms\GroupedListboxField
  BoltMailHelper: ChristopherBolt\BoltTools\Helpers\BoltMailHelper
  BoltShortCodeHelper: ChristopherBolt\BoltTools\Helpers\BoltShortCodeHelper
  BoltIteratorFunctions: ChristopherBolt\BoltTools\Lists\BoltIteratorFunctions
  LimitedPaginatedList: ChristopherBolt\BoltTools\Lists\LimitedPaginatedList
  SortedLimitedPaginatedList: ChristopherBolt\BoltTools\Lists\SortedLimitedPaginatedList
  BoltFulltextSearchable: ChristopherBolt\BoltTools\Search\BoltFulltextSearchable
  BoltSearchForm: ChristopherBolt\BoltTools\Search\BoltSearchForm
  BoltSearchIndexedSiteTree: ChristopherBolt\BoltTools\Search\BoltSearchIndexedSiteTree
  SVGTemplate: ChristopherBolt\BoltTools\View\SVGTemplate
  SVGTemplateProvider: ChristopherBolt\BoltTools\View\SVGTemplateProvider
