---
Name: bolttools
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltToolsLeftAndMain

SilverStripe\ORM\FieldType\DBField:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltDBFieldExtension

SilverStripe\ORM\FieldType\DBText:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltTextExtension

SilverStripe\Security\Member:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltMember

# Linkable
Sheadawson\Linkable\Models\Link:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltLink
    - ChristopherBolt\BoltTools\Extensions\DefaultCan

Sheadawson\Linkable\Forms\LinkField:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltLinkField

# Blog
SilverStripe\Blog\Model\Blog:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlog

SilverStripe\Blog\Controllers\BlogController:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogController

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogPost

SilverStripe\Blog\Controllers\BlogPostController:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogPostController

SilverStripe\Blog\Model\BlogCategory:
  default_sort: 'Title ASC'
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogCategory

SilverStripe\Blog\Model\BlogTag:
  default_sort: 'Title ASC'

# Content Modules
ChristopherBolt\ContentModules\ContentModule:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\DefaultCan

ChristopherBolt\ContentModules\ContentModuleArea:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\DefaultCan
