---
Name: bolttools
After:
  - 'framework/*'
  - 'cms/*'
---
# SS Core
SiteTree_Controller:
  extensions:
   - BoltSiteTree_Controller

LeftAndMain:
  extensions:
    - BoltToolsLeftAndMain

DBField:
  extensions:
    - BoltDBFieldExtension
    
Text:
  extensions:
    - BoltTextExtension

Member:
  extensions:
    - BoltMember

# Linkable
Sheadawson\Linkable\Models\Link:
  extensions:
    - BoltLink
    - DefaultCan

Sheadawson\Linkable\Forms\LinkField:
  extensions:
    - BoltLinkField

# Blog
SilverStripe\Blog\Model\Blog:
  extensions:
    - BoltBlog

SilverStripe\Blog\Controllers\BlogController:
  extensions:
    - BoltBlog_Controller

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - BoltBlogPost

SilverStripe\Blog\Controllers\BlogPostController:
  extensions:
    - BoltBlogPost_Controller

SilverStripe\Blog\Model\BlogCategory:
  default_sort: 'Title ASC'
  extensions:
    - BoltBlogCategory

SilverStripe\Blog\Model\BlogTag:
  default_sort: 'Title ASC'

# Content Modules
ChristopherBolt\ContentModules\ContentModule:
  extensions:
    - ChristopherBolt\BoltTools\DefaultCan

ChristopherBolt\ContentModules\ContentModuleArea:
  extensions:
    - ChristopherBolt\BoltTools\DefaultCan
