---
Name: bolttools
---
# CMS
SilverStripe\Admin\LeftAndMain:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltToolsLeftAndMain

SilverStripe\ORM\FieldType\DBField:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltDBFieldExtension

SilverStripe\ORM\FieldType\DBText:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltTextExtension

SilverStripe\Security\Member:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltMember
    
SilverStripe\CMS\Model\SiteTree:
  extensions:
   - ChristopherBolt\BoltTools\Extensions\BoltSiteTree
   - ChristopherBolt\PublishWithMe\PublishWithMe
   
SilverStripe\CMS\Controllers\ContentController:
  extensions:
   - ChristopherBolt\BoltTools\Extensions\BoltContentController

# Custom site settings
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltSiteConfig

# Linkable
Sheadawson\Linkable\Models\Link:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltLink
    - ChristopherBolt\BoltTools\Extensions\DefaultCan

Sheadawson\Linkable\Forms\LinkField:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltLinkField

# Blog
SilverStripe\Blog\Model\Blog:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlog

SilverStripe\Blog\Model\BlogController:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogController

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogPost

SilverStripe\Blog\Model\BlogPostController:
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogPostController

SilverStripe\Blog\Model\BlogCategory:
  default_sort: 'Title ASC'
  extensions:
    - ChristopherBolt\BoltTools\Extensions\BoltBlogCategory

SilverStripe\Blog\Model\BlogTag:
  default_sort: 'Title ASC'

# Tracking codes
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        CustomMiddleware: '%$ChristopherBolt\BoltTools\Middleware\AddTrackingScriptsMiddleware'